site_name: sxs

repo_url: https://github.com/sxs-collaboration/sxs

plugins:
  - mktheapidocs:
      modules:
        - "sxs": sxs
          section: api
          source_repo: "https://github.com/sxs-collaboration/sxs/blob/main"

theme:
  name: 'readthedocs'

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
